# Generated by Django 2.2.5 on 2019-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0003_auto_20191211_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='codeID',
            field=models.CharField(max_length=6, verbose_name='OrgID'),
        ),
    ]
