# Generated by Django 2.2.5 on 2019-12-11 16:17

import SanitationHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0006_auto_20191211_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='codeID',
            field=models.CharField(default=SanitationHub.models.generateRandomValue, max_length=6, unique=True, verbose_name='OrgID'),
        ),
    ]
