# Generated by Django 2.2.5 on 2019-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0008_auto_20191213_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='filename',
            field=models.FileField(upload_to='dsfiles/', verbose_name='Filename'),
        ),
    ]
