# Generated by Django 2.2.5 on 2019-12-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0009_auto_20191216_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IpAdd'),
        ),
    ]
