# Generated by Django 2.2.5 on 2020-01-17 12:32

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0010_auto_20191216_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=stdimage.models.StdImageField(blank=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
