# Generated by Django 2.2.5 on 2020-01-17 12:54

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0011_auto_20200117_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=stdimage.models.StdImageField(blank=True, upload_to='user_pics', verbose_name='Profile Picture'),
        ),
    ]
